#!/usr/bin/env bash
# setup-ssh.sh — two ed25519 keypairs (host, VM), an ssh config block giving you three ways to
# reach the box (<name>-host direct, <name>-vm over the host's LAN, <name> over the internet
# via the Cloudflare Tunnel from setup-tunnel.sh). Third of infra-kit's three scripts.
#
# Provenance: the exact naming/key-per-hop pattern from dino's real ssh config (2026-08-21) --
# ONE bare name (the tunnel path, works from anywhere) plus two explicit fallback names
# (direct-to-host, LAN-to-VM), not three equally-named options a human has to remember the
# tradeoffs of every time.
#
# Usage:
#   INFRA_NAME=myworker INFRA_DOMAIN=myworker.example.com \
#   INFRA_HOST_IP=<host's LAN or public IP> INFRA_HOST_USER=<user on that host> \
#   INFRA_VM_USER=ubuntu \
#   ./setup-ssh.sh
# Prints an ssh config block to stdout -- append it to ~/.ssh/config yourself (this script
# never edits that file directly; too easy to double-append across re-runs otherwise).
set -euo pipefail

NAME="${INFRA_NAME:?set INFRA_NAME}"
DOMAIN="${INFRA_DOMAIN:?set INFRA_DOMAIN (same value used in setup-tunnel.sh)}"
HOST_IP="${INFRA_HOST_IP:?set INFRA_HOST_IP -- the multipass hosts own reachable address}"
HOST_USER="${INFRA_HOST_USER:?set INFRA_HOST_USER -- your user on the host machine}"
VM_USER="${INFRA_VM_USER:-ubuntu}"
KEY_DIR="${INFRA_KEY_DIR:-$HOME/.ssh/$NAME}"

log() { printf '[setup-ssh] %s\n' "$*" >&2; }

mkdir -p "$KEY_DIR"

# --- 1. keypairs -----------------------------------------------------------------------------
for role in host vm; do
  KEY="$KEY_DIR/${NAME}-${role}_ed25519"
  if [ -f "$KEY" ]; then
    log "$role key already exists at $KEY -- not overwriting"
  else
    log "generating $role key at $KEY"
    ssh-keygen -t ed25519 -f "$KEY" -N "" -C "$NAME-$role" -q
  fi
done

# --- 2. install the VM key's pubkey into the VM's authorized_keys ---------------------------
VM_PUB="$KEY_DIR/${NAME}-vm_ed25519.pub"
log "installing VM pubkey into $NAME authorized_keys (via multipass, no ssh round-trip needed)..."
multipass exec "$NAME" -- bash -c "
  mkdir -p ~/.ssh && chmod 700 ~/.ssh
  grep -qF \"\$(cat)\" ~/.ssh/authorized_keys 2>/dev/null || cat >> ~/.ssh/authorized_keys
  chmod 600 ~/.ssh/authorized_keys
" < "$VM_PUB"
log "VM pubkey installed"

# --- 3. VM's own known_hosts (LAN IP + tunnel hostname -- same key, both names) --------------
VM_IP="$(multipass info "$NAME" --format csv | tail -1 | cut -d, -f3)"
KH_FILE="$KEY_DIR/${NAME}-vm_known_hosts"
log "capturing VM host key for $VM_IP and $DOMAIN into $KH_FILE"
: > "$KH_FILE"
ssh-keyscan -t ed25519 "$VM_IP" 2>/dev/null | sed "s/^$VM_IP/$VM_IP/" >> "$KH_FILE"
# The tunnel hostname presents the SAME host key as the LAN IP (it's the same sshd) -- copy the
# key line under the tunnel's hostname too, rather than keyscan through the tunnel (which needs
# cloudflared access already working -- chicken/egg on a first run).
KEY_LINE=$(awk -v ip="$VM_IP" '$1==ip {$1=""; print}' "$KH_FILE" | sed 's/^ //')
echo "$DOMAIN $KEY_LINE" >> "$KH_FILE"

# --- 4. print the config block ----------------------------------------------------------------
cat <<EOF

# --- $NAME — append below to ~/.ssh/config (generated by infra-kit/setup-ssh.sh) -----------
#
#   $NAME        the VM, over the internet via Cloudflare Tunnel -- canonical bare name,
#                works from anywhere, doesn't need $NAME-host reachable.
#   $NAME-host   the physical/cloud host ($HOST_IP)
#   $NAME-vm     the VM over the host's LAN -- fast-path fallback when you're already there.

Host $NAME-host
  HostName $HOST_IP
  User $HOST_USER
  IdentityFile $KEY_DIR/${NAME}-host_ed25519
  IdentitiesOnly yes
  ServerAliveInterval 30
  ServerAliveCountMax 6
  StrictHostKeyChecking accept-new

Host $NAME-vm
  HostName $VM_IP
  ProxyJump $NAME-host
  User $VM_USER
  IdentityFile $KEY_DIR/${NAME}-vm_ed25519
  IdentitiesOnly yes
  UserKnownHostsFile $KH_FILE
  StrictHostKeyChecking accept-new
  ServerAliveInterval 30
  ServerAliveCountMax 6

Host $NAME
  # /ssh is a path-scoped ingress rule on the tunnel (ssh://localhost:22) -- see
  # setup-tunnel.sh. Requires local cloudflared installed (brew install cloudflared, or
  # https://developers.cloudflare.com/cloudflare-one/connections/connect-networks/downloads/).
  HostName $DOMAIN
  User $VM_USER
  ProxyCommand cloudflared access ssh --hostname $DOMAIN/ssh
  IdentityFile $KEY_DIR/${NAME}-vm_ed25519
  IdentitiesOnly yes
  UserKnownHostsFile $KH_FILE
  StrictHostKeyChecking accept-new
  # Multiplexing -- this path pays a full cloudflared negotiation on EVERY separate ssh
  # invocation with no reuse (measured on dino, 2026-08-22: ~1.5-2.6s per call vs ~180ms for
  # the LAN path). Sharing one underlying connection across commands run within 10 minutes of
  # each other makes every call after the first near-instant. Socket lives in /tmp, not under
  # this repo -- a stale one surviving a VM rebuild would otherwise silently connect to
  # nothing, or the wrong thing, until ControlPersist expires.
  ControlMaster auto
  ControlPath /tmp/${NAME}-ssh-%r@%h:%p
  ControlPersist 10m
# --- end $NAME -------------------------------------------------------------------------------
EOF

log ""
log "append the block above to ~/.ssh/config, then test:"
log "  ssh $NAME-host true   # direct"
log "  ssh $NAME-vm true     # via host's LAN"
log "  ssh $NAME true        # via the internet, needs local cloudflared"
log "  (the first '$NAME' call pays the full tunnel-negotiation cost; every call after it"
log "   within 10 minutes reuses the same connection via ControlMaster and is near-instant)"
